package:
  name: libtest
  version: "0.1"

source:
  path: .

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/CSC380Team8/conda-test
  license: MIT
  license_file: LICENSE
